import { Component, inject } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
@Component({standalone:true,template:`<section class="container section"><p class="eyebrow">Mon compte</p><h1>Tableau de bord</h1><div class="three"><article class="card"><h2>Mes commandes</h2><p>Consultez vos prestations et leur historique.</p></article><article class="card"><h2>Mon profil</h2><p>Mettez à jour vos coordonnées.</p></article><article class="card"><h2>Mes avis</h2><p>Partagez votre expérience après une commande terminée.</p></article></div><p class="alert">Les écrans détaillés de gestion des commandes sont planifiés dans le prochain lot.</p></section>`})
export class UserDashboardComponent{}
@Component({standalone:true,template:`<section class="container section"><p class="eyebrow">Nouvelle prestation</p><h1>Créer une commande</h1><p>Menu sélectionné : <strong>{{slug}}</strong></p><div class="alert">Le formulaire de commande transactionnel et son aperçu tarifaire restent à raccorder à l’API.</div></section>`})
export class OrderCreateComponent{private route=inject(ActivatedRoute);slug=this.route.snapshot.paramMap.get('slug');}
@Component({standalone:true,template:`<section class="container section"><p class="eyebrow">Espace équipe</p><h1>Tableau de bord employé</h1><div class="three"><article class="card"><h2>Commandes</h2><p>Transitions et filtres métier.</p></article><article class="card"><h2>Menus et plats</h2><p>Catalogue, stock et allergènes.</p></article><article class="card"><h2>Avis et horaires</h2><p>Modération et disponibilité.</p></article></div><p class="alert">Les interfaces CRUD sont structurées mais leurs endpoints restent à implémenter.</p></section>`})
export class EmployeeDashboardComponent{}
@Component({standalone:true,template:`<section class="container section"><p class="eyebrow">Administration</p><h1>Pilotage de l’activité</h1><div class="three"><article class="card"><h2>Employés</h2><p>Création et désactivation des comptes.</p></article><article class="card"><h2>Chiffre d’affaires</h2><p>Vue agrégée depuis MongoDB.</p></article><article class="card"><h2>Menus populaires</h2><p>Classement des prestations.</p></article></div><p class="alert">Les statistiques MongoDB et la gestion des employés restent à raccorder.</p></section>`})
export class AdminDashboardComponent{}
